version: '3.3'

services:

  hologram-mart:
    container_name: hologram-mart
    build: ..
    image: max2wms/hologram-mart
    ports:
      - "80:63145"
    networks:
      - hologram_mart
    depends_on:
      - db

  db:
    container_name: db
    # TODO: pin down a specific version of mongo
    image: mongo
    environment:
      - MONGO_DATA_DIR=/data/db
      - MONGO_LOG_DIR=/dev/null
    volumes:
      - "mongo_db:/data/db"
    networks:
      - hologram_mart
    command: mongod --logpath=/dev/null # --quiet

volumes:
  mongo_db:

networks:
  hologram_mart: