version: '3.3'

services:

  hologram-mart:
    container_name: hologram-mart
    # TODO: might want to pin down a specific version of this image
    # TODO: create a Dockerfile for this image
    image: max2wms/angular-dev-env
    volumes:
      - ..:/app
    ports:
      - "80:63145"
    networks:
      - hologram_mart
    command: bash -c "NODE_ENV=docker nodemon"
    depends_on:
      - db

  db:
    container_name: db
    # TODO: pin down a specific version of mongo
    image: mongo
    environment:
      - MONGO_DATA_DIR=/data/db
      - MONGO_LOG_DIR=/dev/null
    volumes:
      - "mongo_db:/data/db"
    networks:
      - hologram_mart
    command: mongod --logpath=/dev/null # --quiet

volumes:
  mongo_db:

networks:
  hologram_mart:
