version: '3.3'

services:

  hologram-mart-client:
    container_name: hologram-mart-client
    image: max2wms/hologram-mart-client
    ports:
      - '443:443'
      - '80:80'
    networks:
      - hologram_mart
    depends_on:
      - hologram-mart-server

  hologram-mart-server:
    container_name: hologram-mart-server
    image: max2wms/hologram-mart-server
    ports:
      - "63145:63145"
    networks:
      - hologram_mart
    command: bash -c "NODE_ENV=docker node server"
    depends_on:
      - db
      
  db:
    container_name: db
    # TODO: pin down a specific version of mongo
    image: mongo
    environment:
      - MONGO_DATA_DIR=/data/db
      - MONGO_LOG_DIR=/dev/null
    volumes:
      - "mongo_db:/data/db"
    networks:
      - hologram_mart
    command: mongod --logpath=/dev/null # --quiet

volumes:
  mongo_db:

networks:
  hologram_mart: